#==========================  Modules configuration =============================
filebeat.modules:

#---------------------------- Elasticsearch Module ----------------------------
- module: elasticsearch
  # Server log
  server:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

  gc:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

  audit:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

  slowlog:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

  deprecation:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:


filebeat.inputs:
 - type: syslog
   enabled: true
   protocol.udp:
#     # The host and port to receive the new event
     host: "0.0.0.0:5140"

#   # Maximum size of the message received over UDP
#   max_message_size: 10KiBi
json.keys_under_root: true
json.overwrite_keys: true

processors:
  - add_locale: ~
  - add_host_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: nginx.access
      add_error_key: true
      overwrite_keys: true


#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  enabled: true
  hosts: ["elasticsearch:9200"]
  # hosts: ["127.0.0.1:9200"]
  index: "nginx-%{+yyyy.MM.dd}"
# output.console:
#   pretty: true
setup.template.name: "nginx"
setup.template.pattern: "nginx-*"
setup.ilm.enabled: false